### ISSUE TITLE
How does this SkipList implement the theory?

### ISSUE THREAD

**Issue by lancejpollard** [jondubois/proper-skip-list#2]
I asked [this question](https://stackoverflow.com/questions/71134703/why-does-this-javascript-skiplist-implementation-have-nodes-and-groups-which) earlier, which is basically asking how the data model works in proper-skip-list. Could you explain what is happening with the data models and why they are the way they are briefly? I am new to SkipLists and am curious how you applied the theory in this implementation.

Thank you so much for your time!

**Comment by jondubois** [comment]
There are 'nodes' and there are 'node groups'.

In terms of a typical SkipList diagram, a Group represents a wrapper for a set of nodes which are stacked on top of each other up to an arbitrary height and which represent a single key and value (a group represents multiple levels of nodes for the same key). The key and value is stored on the Group (instead of nodes) in order to save memory.

Groups are not connected directly to each other, instead, they are connected to each other indirectly via their nodes.
A Group acts as a directory to allow us to quickly find other nodes which share the same key. It makes it easier to perform operations such as removing all nodes which belong to the same key.

Traversal happens via nodes (not via groups). The `searchPath` array records the path of individual nodes traversed in order to reach the target node; it starts at the top level (where nodes are the most scarce; it's rare for a group to be 20 nodes high for example) and works down to the lowest level (where nodes are the most dense; since every group has at least 1 node) - It only records the last seen node on each layer/level. This search path can be used for insertion since it gives us a reference to the last node (just before the target node) on every layer.

**Comment by lancejpollard** [comment]
Great, thank you! That helps a lot.

**Comment by jondubois** [comment]
Instead of Groups, it should be possible to implement a SkipList using an `up` and/or `down` property on each node (in addition to `prev` and `next`) to navigate the different levels. The advantage of the Group abstraction is that it keeps the code short since each node within the group can be referenced by index; this index represents the level of the node within the skip list. It's also possible to add additional properties to the group such as `isHead` and `isTail` which can help when iterating and avoids duplication of data across multiple nodes.
